type: object
required:
  - id
  - title
  - status
  - created_at
properties:
  id:
    type: integer
  title:
    type: string
  description:
    type: string
    nullable: true
  status:
    type: string
    enum:
      - BACKLOG
      - READY
      - IN_PROGRESS
      - IN_REVIEW
      - IN_TESTING
      - COMPLETED
  created_at:
    type: string
    format: date-time
  completed_at:
    type: string
    format: date-time
    nullable: true
    default: null
